#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

role="$(xprop -id "$wid" | awk '/WM_WINDOW_ROLE/ { gsub(/"/, "", $3); print $3 }')"

if [ "$role" = pop-up ] ; then
    echo "state=floating"
fi
